In [4]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import LabelEncoder

In [2]:
data=pd.read_csv('car.csv')
data.head()

Car_Name  Year  Selling_Price  Present_Price  Kms_Driven Fuel_Type  \
0     ritz  2014           3.35           5.59       27000    Petrol   
1      sx4  2013           4.75           9.54       43000    Diesel   
2     ciaz  2017           7.25           9.85        6900    Petrol   
3  wagon r  2011           2.85           4.15        5200    Petrol   
4    swift  2014           4.60           6.87       42450    Diesel   

  Seller_Type Transmission  Owner  
0      Dealer       Manual      0  
1      Dealer       Manual      0  
2      Dealer       Manual      0  
3      Dealer       Manual      0  
4      Dealer       Manual      0

In [3]:
data.shape

(301, 9)

In [5]:
data.isnull().sum()

Car_Name         0
Year             0
Selling_Price    0
Present_Price    0
Kms_Driven       0
Fuel_Type        0
Seller_Type      0
Transmission     0
Owner            0
dtype: int64

In [6]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 301 entries, 0 to 300
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   Car_Name       301 non-null    object 
 1   Year           301 non-null    int64  
 2   Selling_Price  301 non-null    float64
 3   Present_Price  301 non-null    float64
 4   Kms_Driven     301 non-null    int64  
 5   Fuel_Type      301 non-null    object 
 6   Seller_Type    301 non-null    object 
 7   Transmission   301 non-null    object 
 8   Owner          301 non-null    int64  
dtypes: float64(2), int64(3), object(4)
memory usage: 21.3+ KB


In [7]:
label=LabelEncoder()

In [8]:
data['Fuel_Type']=label.fit_transform(data['Fuel_Type'])
data['Seller_Type']=label.fit_transform(data['Seller_Type'])
data['Transmission']=label.fit_transform(data['Transmission'])
data['Car_Name']=label.fit_transform(data['Car_Name'])
data.head()

Car_Name  Year  Selling_Price  Present_Price  Kms_Driven  Fuel_Type  \
0        90  2014           3.35           5.59       27000          2   
1        93  2013           4.75           9.54       43000          1   
2        68  2017           7.25           9.85        6900          2   
3        96  2011           2.85           4.15        5200          2   
4        92  2014           4.60           6.87       42450          1   

   Seller_Type  Transmission  Owner  
0            0             1      0  
1            0             1      0  
2            0             1      0  
3            0             1      0  
4            0             1      0

In [9]:
x=data[['Car_Name','Fuel_Type','Transmission']]
y=data[['Selling_Price']]

In [10]:
print(x)

     Car_Name  Fuel_Type  Transmission
0          90          2             1
1          93          1             1
2          68          2             1
3          96          2             1
4          92          1             1
..        ...        ...           ...
296        69          1             1
297        66          2             1
298        69          2             1
299        69          1             1
300        66          2             1

[301 rows x 3 columns]


In [11]:
print(y)

     Selling_Price
0             3.35
1             4.75
2             7.25
3             2.85
4             4.60
..             ...
296           9.50
297           4.00
298           3.35
299          11.50
300           5.30

[301 rows x 1 columns]


In [12]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=1)
x.shape,x_train.shape,x_test.shape

((301, 3), (240, 3), (61, 3))

In [13]:
model=LinearRegression()

In [14]:
model.fit(x_train,y_train)

LinearRegression()

In [15]:
model.predict(x_test)

array([[10.06658898],
       [ 4.70281595],
       [ 2.47310994],
       [ 4.12740794],
       [ 2.18540594],
       [ 5.70977995],
       [-0.83548608],
       [ 4.48703795],
       [ 3.69585194],
       [ 3.04851794],
       [ 7.91316947],
       [ 4.48703795],
       [ 3.48007394],
       [ 4.34318595],
       [ 0.45918193],
       [ 5.96680696],
       [ 7.84124347],
       [ 9.71131948],
       [10.57007098],
       [ 7.84124347],
       [ 5.35014995],
       [ 3.69585194],
       [ 8.91577298],
       [ 8.69999498],
       [ 8.62806898],
       [14.072489  ],
       [ 3.69585194],
       [-0.76356008],
       [ 0.38725593],
       [ 1.53807193],
       [ 1.10651593],
       [ 1.32229393],
       [ 4.63088995],
       [13.85235051],
       [13.85235051],
       [ 4.34318595],
       [ 4.77474195],
       [-0.04430007],
       [-0.54778208],
       [ 9.85081098],
       [ 3.69585194],
       [ 8.12894747],
       [ 0.09955193],
       [ 9.56746748],
       [ 8.70435547],
       [ 3

In [16]:
model.predict(x_train)

array([[ 1.75384993],
       [ 8.05702147],
       [ 9.71131948],
       [-0.76356008],
       [ 2.90466594],
       [ 5.42207595],
       [-0.33200407],
       [ 3.83970394],
       [ 1.32229393],
       [ 3.69585194],
       [ 8.41665147],
       [ 3.83970394],
       [ 0.74688593],
       [ 1.68192393],
       [ 5.42207595],
       [ 1.60999793],
       [ 3.69585194],
       [ 9.78324548],
       [ 3.33622194],
       [ 3.26429594],
       [ 1.75384993],
       [ 8.77628147],
       [ 9.13155098],
       [ 2.18540594],
       [ 8.20087347],
       [ 4.70281595],
       [ 1.03458993],
       [-0.97933808],
       [ 4.77474195],
       [ 3.48007394],
       [ 4.99051995],
       [ 5.42207595],
       [ 3.98355594],
       [ 9.13591147],
       [ 8.27279947],
       [ 2.97659194],
       [ 5.13437195],
       [ 2.40118394],
       [ 3.04851794],
       [ 1.96962794],
       [ 3.69585194],
       [ 3.26429594],
       [13.85235051],
       [ 3.48007394],
       [ 7.40532697],
       [ 2

In [17]:
print('Accuracy on Training Data',model.score(x_train,y_train))

Accuracy on Training Data 0.46492432586690735


In [19]:
print('Accuracy on Testing Data',model.score(x_test,y_test))

Accuracy on Testing Data 0.49256446786121566


In [20]:
from sklearn import metrics

In [21]:
prediction=model.predict(x_test)

In [22]:
print(prediction)

[[10.06658898]
 [ 4.70281595]
 [ 2.47310994]
 [ 4.12740794]
 [ 2.18540594]
 [ 5.70977995]
 [-0.83548608]
 [ 4.48703795]
 [ 3.69585194]
 [ 3.04851794]
 [ 7.91316947]
 [ 4.48703795]
 [ 3.48007394]
 [ 4.34318595]
 [ 0.45918193]
 [ 5.96680696]
 [ 7.84124347]
 [ 9.71131948]
 [10.57007098]
 [ 7.84124347]
 [ 5.35014995]
 [ 3.69585194]
 [ 8.91577298]
 [ 8.69999498]
 [ 8.62806898]
 [14.072489  ]
 [ 3.69585194]
 [-0.76356008]
 [ 0.38725593]
 [ 1.53807193]
 [ 1.10651593]
 [ 1.32229393]
 [ 4.63088995]
 [13.85235051]
 [13.85235051]
 [ 4.34318595]
 [ 4.77474195]
 [-0.04430007]
 [-0.54778208]
 [ 9.85081098]
 [ 3.69585194]
 [ 8.12894747]
 [ 0.09955193]
 [ 9.56746748]
 [ 8.70435547]
 [ 3.33622194]
 [ 7.91316947]
 [ 5.49400195]
 [ 8.41665147]
 [ 1.82577593]
 [ 5.20629795]
 [ 1.46614593]
 [ 4.12740794]
 [ 3.48007394]
 [ 2.25733194]
 [ 0.81881193]
 [13.85235051]
 [ 3.12044394]
 [ 5.49400195]
 [ 4.99051995]
 [ 7.76495697]]


In [23]:
# R squared Error
error_score = metrics.r2_score(y_test,prediction)
print("R squared Error : ", error_score)

R squared Error :  0.49256446786121566
